# base image
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

# mkdir and cd
WORKDIR /app

COPY *.sln ./
COPY RRBL/*.csproj RRBL/
COPY RRDL/*.csproj RRDL/
COPY RRTests/*.csproj RRTests/
COPY RRWebUI/*.csproj RRWebUI/
COPY RRModels/*.csproj RRModels/

RUN cd RRWebUI && dotnet restore

# Copy source code
COPY . ./
# CMD /bin/bash

RUN dotnet publish RRWebUI -c Release -o publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime

WORKDIR /app


COPY --from=build /app/publish ./

CMD ["dotnet", "RRWebUI.dll"]
